<%
rerun = File.file?('rerun.txt') ? IO.read('rerun.txt') : ""
rerun_opts = rerun.to_s.strip.empty? ? "--format #{ENV['CUCUMBER_FORMAT'] || 'progress'} features" : "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} #{rerun}"
std_opts = "--format pretty --format html -o reports/cuke.html --strict --tags ~@wip --color"
%>
default: <%= std_opts %> features
wip: --tags @wip:3 --wip features
rerun: <%= rerun_opts %> --format rerun --out rerun.txt --strict --tags ~@wip
canary: <%= std_opts %> --tags @canary features
qa: <%= std_opts %> --tags @qa features
staging: <%= std_opts %> --tags @staging features
production: <%= std_opts %> --tags @production features
